### ISSUE TITLE
默认的children如果为空会有一些问题

### ISSUE THREAD

**Issue by sunjun2009311** [elileo1/extended_wrap#13]
报错信息：Another exception was thrown: 'package:extended_wrap/src/extend_render_wrap.dart': Failed assertion: line 702 pos 12: 'runCount > 0': is not true.
Another exception was thrown: RenderBox was not laid out: ExtendedRenderWrap#5b5d7 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderPositionedBox#ccce5 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderPadding#ab233 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderFlex#a9ba2 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderFlex#15a9d relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderFlex#a9ba2 relayoutBoundary=up2
Another exception was thrown: RenderBox was not laid out: RenderFlex#15a9d relayoutBoundary=up1 NEEDS-PAINT

**Comment by elileo1** [comment]
判断数据是否为空， 为空就别用这个就OK了

**Comment by sunjun2009311** [comment]
也行
