### ISSUE TITLE
Get length of hidden widget ?

### ISSUE THREAD

**Issue by azizarc88** [elileo1/extended_wrap#7]
Hey @elileo1 , your work are best, since flutter warp widget doesnt have max line feature like yours 👍🏻 

But, Is there any way to calculate the number of hidden widget because of max lines ?
since there are some possibility to build overflow widget with text "+3 more"

**Comment by elileo1** [comment]
yes, of course， next version i will add this feature

**Comment by elileo1** [comment]
can calculate them number of hidden widget, but can ot  build overflow widget with text "+3 more

**Comment by elileo1** [comment]
can calculate them number of hidden widget, but can't build overflow widget with text "+3 more, because if callback the number of hidden widget, the overflow widget width  maybe change
